#!/bin/bash

source /etc/X11/xinit/xinputrc

eval $(gpg-agent --daemon --default-cache-ttl 1200 --write-env-file $HOME/.gpg-agent-info)
eval $(dbus-launch --sh-syntax)

export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export TERMINAL='lxterminal'

xmodmap ~/.Xmodmap

lxterminal &
exec i3

